version: "3.1"
services:
  db:
    image: mongo
    restart: always
    container_name: db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  api:
    build: .
    image: api:hml
    restart: on-failure
    container_name: api
    ports:
      - 3000:3000
    environment:
      NODE_ENV: hml
